server.port=9000

spring.datasource.url=jdbc:postgresql://localhost:5432/kutuphane
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.properties.hibernate.default_schema=bank
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.client.registration.github.client-id=Ov23liP4VCE0wDDO3txr
spring.security.oauth2.client.registration.github.client-secret=ecaa17f230ad13ccce3e399e3f4a3ac99fc6bd21

myapp.admin.username=admin
myapp.admin.password=123